### ISSUE TITLE
Update lsapi to 7.2

### ISSUE THREAD

**Issue by lucasRolff** [CpanelInc/scl-php72#1]
Hi,

all scl builds currently use lsapi version 7.1, 7.2 recently got released with a few patches from CloudLinux

```
[Improvement] Added timestamp when directly logging stderr to file.
[Bug Fix] Fixed LSAPI protocol corruption when PHP scripts fork child process. (reported by CloudLinux)
[Big Fix] Fixed uninitialized sa_mask during signal handler setup. (reported with patch by CloudLinux)
[Bug Fix] Fixed wrong string length when trimming long log strings containing trailing newlines. (reported with patch by CloudLinux)
[Bug Fix] Fixed max idle timeout time not resetting properly during socket events. (reported with patch by CloudLinux)
```

**Comment by gitcory** [comment]
Hi Lucas, 
Thanks for the heads up, litespeed also reached out to us to let us know. We'll get it into testing and have the update out in the next release or two, sooner than later if testing goes well.

Thanks again

**Comment by gitcory** [comment]
Sorry, meant to mention this will be handled in Case EA-8170. Thanks.
