### ISSUE TITLE
commit missing from `master`

### ISSUE THREAD

**Issue by celesteking** [CpanelInc/scl-php72#2]
Pretty sus to have 21bca13 in `production` but not in `master`. 

Thanks.

**Comment by gitcory** [comment]
Nothing sus about it really, I just failed to check that our github updating script worked for both master and production. production is what we tell folks should work and be up to date, while master can always be in a broken state (though we don't like to keep it that way) and should be treated as such. 

Either way, my fault, I've corrected it. Thanks for pointing it out!

**Comment by celesteking** [comment]
Same story with `scl-php56`, btw. Thanks.

**Comment by gitcory** [comment]
I was getting there! too fast lol. yeah i just ran through all of them for that change, missed a couple. thanks again for the heads up. they should all be up to date with that case in both master and production shortly or today for sure.

**Comment by celesteking** [comment]
Much appreciated. Happy holidays!

**Comment by gitcory** [comment]
same to you!
